
# Data Science with Databricks

## ML is key to disruption & risk reduction

Being able to ingest and query our banking database is a first step, but this isn't enough to thrive in a very competitive market.

Banking customers now expect real time personalization and protection. Modern data company achieve this with AI.

<style>
.right_box{
  margin: 30px; box-shadow: 10px -10px #CCC; width:650px;height:300px; background-color: #1b3139ff; box-shadow:  0 0 10px  rgba(0,0,0,0.6);
  border-radius:25px;font-size: 35px; float: left; padding: 20px; color: #f9f7f4; }
.badge {
  clear: left; float: left; height: 30px; width: 30px;  display: table-cell; vertical-align: middle; border-radius: 50%; background: #fcba33ff; text-align: center; color: white; margin-right: 10px}
.badge_b { 
  height: 35px}
</style>
<link href='https://fonts.googleapis.com/css?family=DM Sans' rel='stylesheet'>
<div style="font-family: 'DM Sans'">
  <div style="width: 500px; color: #1b3139; margin-left: 50px; float: left">
    <div style="color: #ff5f46; font-size:80px">90%</div>
    <div style="font-size:30px;  margin-top: -20px; line-height: 30px;">
      Enterprise applications will be AI-augmented by 2025 —IDC
    </div>
    <div style="color: #ff5f46; font-size:80px">$10T+</div>
    <div style="font-size:30px;  margin-top: -20px; line-height: 30px;">
       Projected business value creation by AI in 2030 —PWC
    </div>
  </div>
</div>



  <div class="right_box">
      But—huge challenges getting ML to work at scale!<br/><br/>
      Most ML projects still fail before getting to production
  </div>
  
<br style="clear: both">

## Machine learning is data + transforms.

ML is hard because delivering value to business lines isn't only about building a Model. <br>
The ML lifecycle is made of data pipelines: Data-preprocessing, feature engineering, training, inference, monitoring and retraining...<br>
Stepping back, all pipelines are data + code.


<img style="float: right; margin-top: 10px" width="500px" src="https://github.com/databricks-demos/dbdemos-resources/raw/main/images/retail/lakehouse-churn/lakehouse-retail-c360-churn-4.png" />

<img src="https://github.com/databricks-demos/dbdemos-resources/raw/main/images/ds.png" style="float: left;" width="80px"> 
<h3 style="padding: 10px 0px 0px 5px">Marc, as a Data Scientist, needs a data + ML platform accelerating all the ML & DS steps:</h3>

<div style="font-size: 19px; margin-left: 73px; clear: left">
<div class="badge_b"><div class="badge">1</div> Build Data Pipeline supporting real time (with SDP)</div>
<div class="badge_b"><div class="badge">2</div> Data Exploration</div>
<div class="badge_b"><div class="badge">3</div> Feature creation</div>
<div class="badge_b"><div class="badge">4</div> Build & train model</div>
<div class="badge_b"><div class="badge">5</div> Deploy Model (Batch or serverless realtime)</div>
<div class="badge_b"><div class="badge">6</div> Monitoring</div>
</div>

**Marc needs A Lakehouse**. Let's see how we can deploy a real-time Fraud Detection model in production within the Lakehouse


# Fraud Detection - Single click deployment with AutoML

Let's see how we can now leverage the Banking data to build a model rating our Fraud risk on each transaction.

Our first step as Data Scientist is to analyze and build the features we'll use to train our model.

The transaction table enriched with customer data has been saved within our Spark Declarative Pipelines pipeline. All we have to do is read this information, analyze it and start an Auto-ML run.

<img src="https://raw.githubusercontent.com/databricks-demos/dbdemos-resources/main/images/fsi/fraud-detection/fsi-fraud-ds.png" width="1000px">

*Note: Make sure you switched to the "Machine Learning" persona on the top left menu.*

<!-- Collect usage data (view). Remove it to disable collection. View README for more details.  -->
<img width="1px" src="https://ppxrzfxige.execute-api.us-west-2.amazonaws.com/v1/analytics?category=lakehouse&org_id=2162748966026566&notebook=%2F04-Data-Science-ML%2F04.1-AutoML-FSI-fraud&demo_name=lakehouse-fsi-fraud&event=VIEW&path=%2F_dbdemos%2Flakehouse%2Flakehouse-fsi-fraud%2F04-Data-Science-ML%2F04.1-AutoML-FSI-fraud&version=1">

In [0]:
%pip install databricks-sdk==0.36.0 mlflow==2.19.0 databricks-feature-store==0.17.0
dbutils.library.restartPython()

Collecting databricks-sdk==0.36.0
  Downloading databricks_sdk-0.36.0-py3-none-any.whl.metadata (38 kB)
Collecting mlflow==2.19.0
  Downloading mlflow-2.19.0-py3-none-any.whl.metadata (30 kB)
Collecting databricks-feature-store==0.17.0
  Downloading databricks_feature_store-0.17.0-py3-none-any.whl.metadata (3.4 kB)
Requirement already satisfied: requests<3,>=2.28.1 in /databricks/python3/lib/python3.12/site-packages (from databricks-sdk==0.36.0) (2.32.2)
Requirement already satisfied: google-auth~=2.0 in /databricks/python3/lib/python3.12/site-packages (from databricks-sdk==0.36.0) (2.21.0)
Collecting mlflow-skinny==2.19.0 (from mlflow==2.19.0)
  Downloading mlflow_skinny-2.19.0-py3-none-any.whl.metadata (31 kB)
Requirement already satisfied: Flask<4 in /databricks/python3/lib/python3.12/site-packages (from mlflow==2.19.0) (2.2.5)
Requirement already satisfied: Jinja2<4,>=2.11 in /databricks/python3/lib/python3.12/site-packages (from mlflow==2.19.0) (3.1.4)
Requirement already satisfied: alembic!=1.10.0,<2 in /databricks/python3/lib/python3.12/site-packages (from mlflow==2.19.0) (1.14.1)
Collecting docker<8,>=4.0.0 (from mlflow==2.19.0)
  Downloading docker-7.1.0-py3-none-any.whl.metadata (3.8 kB)
Collecting graphene<4 (from mlflow==2.19.0)
  Downloading graphene-3.4.3-py2.py3-none-any.whl.metadata (6.9 kB)
Requirement already satisfied: gunicorn<24 in /databricks/python3/lib/python3.12/site-packages (from mlflow==2.19.0) (20.1.0)
Requirement already satisfied: markdown<4,>=3.3 in /databricks/python3/lib/python3.12/site-packages (from mlflow==2.19.0) (3.4.1)
Requirement already satisfied: matplotlib<4 in /databricks/python3/lib/python3.12/site-packages (from mlflow==2.19.0) (3.8.4)
Requirement already satisfied: numpy<3 in /databricks/python3/lib/python3.12/site-packages (from mlflow==2.19.0) (1.26.4)
Requirement already satisfied: pandas<3 in /databricks/python3/lib/python3.12/site-packages (from mlflow==2.19.0) (1.5.3)
Requirement already satisfied: pyarrow<19,>=4.0.0 in /databricks/python3/lib/python3.12/site-packages (from mlflow==2.19.0) (15.0.2)
Requirement already satisfied: scikit-learn<2 in /databricks/python3/lib/python3.12/site-packages (from mlflow==2.19.0) (1.4.2)
Requirement already satisfied: scipy<2 in /databricks/python3/lib/python3.12/site-packages (from mlflow==2.19.0) (1.13.1)
Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /databricks/python3/lib/python3.12/site-packages (from mlflow==2.19.0) (2.0.30)
Requirement already satisfied: databricks-feature-engineering>=0.2.0 in /databricks/python3/lib/python3.12/site-packages (from databricks-feature-store==0.17.0) (0.10.2)
Requirement already satisfied: cachetools<6,>=5.0.0 in /databricks/python3/lib/python3.12/site-packages (from mlflow-skinny==2.19.0->mlflow==2.19.0) (5.3.3)
Requirement already satisfied: click<9,>=7.0 in /databricks/python3/lib/python3.12/site-packages (from mlflow-skinny==2.19.0->mlflow==2.19.0) (8.1.7)
Requirement already satisfied: cloudpickle<4 in /databricks/python3/lib/python3.12/site-packages (from mlflow-skinny==2.19.0->mlflow==2.19.0) (2.2.1)
Requirement already satisfied: gitpython<4,>=3.1.9 in /databricks/python3/lib/python3.12/site-packages (from mlflow-skinny==2.19.0->mlflow==2.19.0) (3.1.37)
Requirement already satisfied: importlib_metadata!=4.7.0,<9,>=3.7.0 in /databricks/python3/lib/python3.12/site-packages (from mlflow-skinny==2.19.0->mlflow==2.19.0) (6.0.0)
Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in /databricks/python3/lib/python3.12/site-packages (from mlflow-skinny==2.19.0->mlflow==2.19.0) (1.32.0)
Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in /databricks/python3/lib/python3.12/site-packages (from mlflow-skinny==2.19.0->mlflow==2.19.0) (1.32.0)
Requirement already satisfied: packaging<25 in /databricks/python3/lib/python3.12/site-packages (from mlflow-skinny==2.19.0->mlflow==2.19.0) (24.1)
Requirement already satisfied: protobuf<6,>=3.12.0 in /databricks/python3/lib/python3.12/site-packages (from mlflow-skinny==2.19.0->mlflow==2.19.0) (4.24.1)
Requirement already satisfied: pyyaml<7,>=5.1 in /databricks/python3/lib/python3.12/site-packages (from mlflow-skinny==2.19.0->mlflow==2.19.0) (6.0.1)
Requirement already satisfied: sqlparse<1,>=0.4.0 in /databricks/python3/lib/python3.12/site-packages (from mlflow-skinny==2.19.0->mlflow==2.19.0) (0.4.2)
Requirement already satisfied: Mako in /databricks/python3/lib/python3.12/site-packages (from alembic!=1.10.0,<2->mlflow==2.19.0) (1.2.0)
Requirement already satisfied: typing-extensions>=4 in /databricks/python3/lib/python3.12/site-packages (from alembic!=1.10.0,<2->mlflow==2.19.0) (4.11.0)
Requirement already satisfied: boto3<2,>=1.16.7 in /databricks/python3/lib/python3.12/site-packages (from databricks-feature-engineering>=0.2.0->databricks-feature-store==0.17.0) (1.34.69)
Requirement already satisfied: dbl-tempo<1,>=0.1.26 in /databricks/python3/lib/python3.12/site-packages (from databricks-feature-engineering>=0.2.0->databricks-feature-store==0.17.0) (0.1.26)
Requirement already satisfied: azure-cosmos==4.3.1 in /databricks/python3/lib/python3.12/site-packages (from databricks-feature-engineering>=0.2.0->databricks-feature-store==0.17.0) (4.3.1)
Requirement already satisfied: azure-core<2.0.0,>=1.23.0 in /databricks/python3/lib/python3.12/site-packages (from azure-cosmos==4.3.1->databricks-feature-engineering>=0.2.0->databricks-feature-store==0.17.0) (1.33.0)
Requirement already satisfied: urllib3>=1.26.0 in /databricks/python3/lib/python3.12/site-packages (from docker<8,>=4.0.0->mlflow==2.19.0) (1.26.16)
Requirement already satisfied: Werkzeug>=2.2.2 in /databricks/python3/lib/python3.12/site-packages (from Flask<4->mlflow==2.19.0) (3.0.3)
Requirement already satisfied: itsdangerous>=2.0 in /databricks/python3/lib/python3.12/site-packages (from Flask<4->mlflow==2.19.0) (2.2.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /databricks/python3/lib/python3.12/site-packages (from google-auth~=2.0->databricks-sdk==0.36.0) (0.2.8)
Requirement already satisfied: rsa<5,>=3.1.4 in /databricks/python3/lib/python3.12/site-packages (from google-auth~=2.0->databricks-sdk==0.36.0) (4.9)
Requirement already satisfied: six>=1.9.0 in /usr/lib/python3/dist-packages (from google-auth~=2.0->databricks-sdk==0.36.0) (1.16.0)
Requirement already satisfied: graphql-core<3.3,>=3.1 in /databricks/python3/lib/python3.12/site-packages (from graphene<4->mlflow==2.19.0) (3.2.4)
Collecting graphql-relay<3.3,>=3.1 (from graphene<4->mlflow==2.19.0)
  Downloading graphql_relay-3.2.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: python-dateutil<3,>=2.7.0 in /databricks/python3/lib/python3.12/site-packages (from graphene<4->mlflow==2.19.0) (2.9.0.post0)
Requirement already satisfied: setuptools>=3.0 in /usr/local/lib/python3.12/dist-packages (from gunicorn<24->mlflow==2.19.0) (74.0.0)
Requirement already satisfied: MarkupSafe>=2.0 in /databricks/python3/lib/python3.12/site-packages (from Jinja2<4,>=2.11->mlflow==2.19.0) (2.1.3)
Requirement already satisfied: contourpy>=1.0.1 in /databricks/python3/lib/python3.12/site-packages (from matplotlib<4->mlflow==2.19.0) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /databricks/python3/lib/python3.12/site-packages (from matplotlib<4->mlflow==2.19.0) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /databricks/python3/lib/python3.12/site-packages (from matplotlib<4->mlflow==2.19.0) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /databricks/python3/lib/python3.12/site-packages (from matplotlib<4->mlflow==2.19.0) (1.4.4)
Requirement already satisfied: pillow>=8 in /databricks/python3/lib/python3.12/site-packages (from matplotlib<4->mlflow==2.19.0) (10.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /databricks/python3/lib/python3.12/site-packages (from matplotlib<4->mlflow==2.19.0) (3.0.9)
Requirement already satisfied: pytz>=2020.1 in /databricks/python3/lib/python3.12/site-packages (from pandas<3->mlflow==2.19.0) (2024.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /databricks/python3/lib/python3.12/site-packages (from requests<3,>=2.28.1->databricks-sdk==0.36.0) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /databricks/python3/lib/python3.12/site-packages (from requests<3,>=2.28.1->databricks-sdk==0.36.0) (3.7)
Requirement already satisfied: certifi>=2017.4.17 in /databricks/python3/lib/python3.12/site-packages (from requests<3,>=2.28.1->databricks-sdk==0.36.0) (2024.6.2)
Requirement already satisfied: joblib>=1.2.0 in /databricks/python3/lib/python3.12/site-packages (from scikit-learn<2->mlflow==2.19.0) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /databricks/python3/lib/python3.12/site-packages (from scikit-learn<2->mlflow==2.19.0) (2.2.0)
Requirement already satisfied: greenlet!=0.4.17 in /databricks/python3/lib/python3.12/site-packages (from sqlalchemy<3,>=1.4.0->mlflow==2.19.0) (3.0.1)
Requirement already satisfied: botocore<1.35.0,>=1.34.69 in /databricks/python3/lib/python3.12/site-packages (from boto3<2,>=1.16.7->databricks-feature-engineering>=0.2.0->databricks-feature-store==0.17.0) (1.34.69)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /databricks/python3/lib/python3.12/site-packages (from boto3<2,>=1.16.7->databricks-feature-engineering>=0.2.0->databricks-feature-store==0.17.0) (1.0.1)
Requirement already satisfied: s3transfer<0.11.0,>=0.10.0 in /databricks/python3/lib/python3.12/site-packages (from boto3<2,>=1.16.7->databricks-feature-engineering>=0.2.0->databricks-feature-store==0.17.0) (0.10.2)
Requirement already satisfied: ipython in /databricks/python3/lib/python3.12/site-packages (from dbl-tempo<1,>=0.1.26->databricks-feature-engineering>=0.2.0->databricks-feature-store==0.17.0) (8.25.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /databricks/python3/lib/python3.12/site-packages (from gitpython<4,>=3.1.9->mlflow-skinny==2.19.0->mlflow==2.19.0) (4.0.11)
Requirement already satisfied: zipp>=0.5 in /databricks/python3/lib/python3.12/site-packages (from importlib_metadata!=4.7.0,<9,>=3.7.0->mlflow-skinny==2.19.0->mlflow==2.19.0) (3.17.0)
Requirement already satisfied: azure-storage-file-datalake>12 in /databricks/python3/lib/python3.12/site-packages (from mlflow-skinny[databricks]<3,>=2.16.0->databricks-feature-engineering>=0.2.0->databricks-feature-store==0.17.0) (12.17.0)
Requirement already satisfied: google-cloud-storage>=1.30.0 in /databricks/python3/lib/python3.12/site-packages (from mlflow-skinny[databricks]<3,>=2.16.0->databricks-feature-engineering>=0.2.0->databricks-feature-store==0.17.0) (2.10.0)
Requirement already satisfied: deprecated>=1.2.6 in /databricks/python3/lib/python3.12/site-packages (from opentelemetry-api<3,>=1.9.0->mlflow-skinny==2.19.0->mlflow==2.19.0) (1.2.18)
Requirement already satisfied: opentelemetry-semantic-conventions==0.53b0 in /databricks/python3/lib/python3.12/site-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==2.19.0->mlflow==2.19.0) (0.53b0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /databricks/python3/lib/python3.12/site-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk==0.36.0) (0.4.8)
Requirement already satisfied: azure-storage-blob>=12.23.0 in /databricks/python3/lib/python3.12/site-packages (from azure-storage-file-datalake>12->mlflow-skinny[databricks]<3,>=2.16.0->databricks-feature-engineering>=0.2.0->databricks-feature-store==0.17.0) (12.23.0)
Requirement already satisfied: isodate>=0.6.1 in /databricks/python3/lib/python3.12/site-packages (from azure-storage-file-datalake>12->mlflow-skinny[databricks]<3,>=2.16.0->databricks-feature-engineering>=0.2.0->databricks-feature-store==0.17.0) (0.6.1)
Requirement already satisfied: wrapt<2,>=1.10 in /databricks/python3/lib/python3.12/site-packages (from deprecated>=1.2.6->opentelemetry-api<3,>=1.9.0->mlflow-skinny==2.19.0->mlflow==2.19.0) (1.14.1)
Requirement already satisfied: smmap<6,>=3.0.1 in /databricks/python3/lib/python3.12/site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==2.19.0->mlflow==2.19.0) (5.0.0)
Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5 in /databricks/python3/lib/python3.12/site-packages (from google-cloud-storage>=1.30.0->mlflow-skinny[databricks]<3,>=2.16.0->databricks-feature-engineering>=0.2.0->databricks-feature-store==0.17.0) (2.20.0)
Requirement already satisfied: google-cloud-core<3.0dev,>=2.3.0 in /databricks/python3/lib/python3.12/site-packages (from google-cloud-storage>=1.30.0->mlflow-skinny[databricks]<3,>=2.16.0->databricks-feature-engineering>=0.2.0->databricks-feature-store==0.17.0) (2.4.3)
Requirement already satisfied: google-resumable-media>=2.3.2 in /databricks/python3/lib/python3.12/site-packages (from google-cloud-storage>=1.30.0->mlflow-skinny[databricks]<3,>=2.16.0->databricks-feature-engineering>=0.2.0->databricks-feature-store==0.17.0) (2.7.2)
Requirement already satisfied: decorator in /databricks/python3/lib/python3.12/site-packages (from ipython->dbl-tempo<1,>=0.1.26->databricks-feature-engineering>=0.2.0->databricks-feature-store==0.17.0) (5.1.1)
Requirement already satisfied: jedi>=0.16 in /databricks/python3/lib/python3.12/site-packages (from ipython->dbl-tempo<1,>=0.1.26->databricks-feature-engineering>=0.2.0->databricks-feature-store==0.17.0) (0.19.1)
Requirement already satisfied: matplotlib-inline in /databricks/python3/lib/python3.12/site-packages (from ipython->dbl-tempo<1,>=0.1.26->databricks-feature-engineering>=0.2.0->databricks-feature-store==0.17.0) (0.1.6)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in /databricks/python3/lib/python3.12/site-packages (from ipython->dbl-tempo<1,>=0.1.26->databricks-feature-engineering>=0.2.0->databricks-feature-store==0.17.0) (3.0.43)
Requirement already satisfied: pygments>=2.4.0 in /databricks/python3/lib/python3.12/site-packages (from ipython->dbl-tempo<1,>=0.1.26->databricks-feature-engineering>=0.2.0->databricks-feature-store==0.17.0) (2.15.1)
Requirement already satisfied: stack-data in /databricks/python3/lib/python3.12/site-packages (from ipython->dbl-tempo<1,>=0.1.26->databricks-feature-engineering>=0.2.0->databricks-feature-store==0.17.0) (0.2.0)
Requirement already satisfied: traitlets>=5.13.0 in /databricks/python3/lib/python3.12/site-packages (from ipython->dbl-tempo<1,>=0.1.26->databricks-feature-engineering>=0.2.0->databricks-feature-store==0.17.0) (5.14.3)
Requirement already satisfied: pexpect>4.3 in /databricks/python3/lib/python3.12/site-packages (from ipython->dbl-tempo<1,>=0.1.26->databricks-feature-engineering>=0.2.0->databricks-feature-store==0.17.0) (4.8.0)
Requirement already satisfied: cryptography>=2.1.4 in /databricks/python3/lib/python3.12/site-packages (from azure-storage-blob>=12.23.0->azure-storage-file-datalake>12->mlflow-skinny[databricks]<3,>=2.16.0->databricks-feature-engineering>=0.2.0->databricks-feature-store==0.17.0) (42.0.5)
Requirement already satisfied: googleapis-common-protos<2.0.dev0,>=1.56.2 in /databricks/python3/lib/python3.12/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-storage>=1.30.0->mlflow-skinny[databricks]<3,>=2.16.0->databricks-feature-engineering>=0.2.0->databricks-feature-store==0.17.0) (1.70.0)
Requirement already satisfied: proto-plus<2.0.0dev,>=1.22.3 in /databricks/python3/lib/python3.12/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-storage>=1.30.0->mlflow-skinny[databricks]<3,>=2.16.0->databricks-feature-engineering>=0.2.0->databricks-feature-store==0.17.0) (1.26.1)
Requirement already satisfied: google-crc32c<2.0dev,>=1.0 in /databricks/python3/lib/python3.12/site-packages (from google-resumable-media>=2.3.2->google-cloud-storage>=1.30.0->mlflow-skinny[databricks]<3,>=2.16.0->databricks-feature-engineering>=0.2.0->databricks-feature-store==0.17.0) (1.7.1)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in /databricks/python3/lib/python3.12/site-packages (from jedi>=0.16->ipython->dbl-tempo<1,>=0.1.26->databricks-feature-engineering>=0.2.0->databricks-feature-store==0.17.0) (0.8.3)
Requirement already satisfied: ptyprocess>=0.5 in /databricks/python3/lib/python3.12/site-packages (from pexpect>4.3->ipython->dbl-tempo<1,>=0.1.26->databricks-feature-engineering>=0.2.0->databricks-feature-store==0.17.0) (0.7.0)
Requirement already satisfied: wcwidth in /databricks/python3/lib/python3.12/site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython->dbl-tempo<1,>=0.1.26->databricks-feature-engineering>=0.2.0->databricks-feature-store==0.17.0) (0.2.5)
Requirement already satisfied: executing in /databricks/python3/lib/python3.12/site-packages (from stack-data->ipython->dbl-tempo<1,>=0.1.26->databricks-feature-engineering>=0.2.0->databricks-feature-store==0.17.0) (0.8.3)
Requirement already satisfied: asttokens in /databricks/python3/lib/python3.12/site-packages (from stack-data->ipython->dbl-tempo<1,>=0.1.26->databricks-feature-engineering>=0.2.0->databricks-feature-store==0.17.0) (2.0.5)
Requirement already satisfied: pure-eval in /databricks/python3/lib/python3.12/site-packages (from stack-data->ipython->dbl-tempo<1,>=0.1.26->databricks-feature-engineering>=0.2.0->databricks-feature-store==0.17.0) (0.2.2)
Requirement already satisfied: cffi>=1.12 in /databricks/python3/lib/python3.12/site-packages (from cryptography>=2.1.4->azure-storage-blob>=12.23.0->azure-storage-file-datalake>12->mlflow-skinny[databricks]<3,>=2.16.0->databricks-feature-engineering>=0.2.0->databricks-feature-store==0.17.0) (1.16.0)
Requirement already satisfied: pycparser in /databricks/python3/lib/python3.12/site-packages (from cffi>=1.12->cryptography>=2.1.4->azure-storage-blob>=12.23.0->azure-storage-file-datalake>12->mlflow-skinny[databricks]<3,>=2.16.0->databricks-feature-engineering>=0.2.0->databricks-feature-store==0.17.0) (2.21)
Downloading databricks_sdk-0.36.0-py3-none-any.whl (569 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/569.1 kB ? eta -:--:--
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 563.2/569.1 kB 19.0 MB/s eta 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 569.1/569.1 kB 14.0 MB/s eta 0:00:00
Downloading mlflow-2.19.0-py3-none-any.whl (27.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/27.4 MB ? eta -:--:--
   ━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.7/27.4 MB 201.0 MB/s eta 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━ 15.2/27.4 MB 240.4 MB/s eta 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━ 22.8/27.4 MB 227.3 MB/s eta 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 27.4/27.4 MB 231.9 MB/s eta 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 27.4/27.4 MB 231.9 MB/s eta 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.4/27.4 MB 97.5 MB/s eta 0:00:00
Downloading databricks_feature_store-0.17.0-py3-none-any.whl (4.2 kB)
Downloading mlflow_skinny-2.19.0-py3-none-any.whl (5.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/5.9 MB ? eta -:--:--
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 5.8/5.9 MB 297.8 MB/s eta 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.9/5.9 MB 163.0 MB/s eta 0:00:00
Downloading docker-7.1.0-py3-none-any.whl (147 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/147.8 kB ? eta -:--:--
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 147.8/147.8 kB 25.5 MB/s eta 0:00:00
Downloading graphene-3.4.3-py2.py3-none-any.whl (114 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/114.9 kB ? eta -:--:--
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.9/114.9 kB 18.1 MB/s eta 0:00:00
Downloading graphql_relay-3.2.0-py3-none-any.whl (16 kB)
Installing collected packages: graphql-relay, graphene, docker, databricks-sdk, mlflow-skinny, mlflow, databricks-feature-store
  Attempting uninstall: databricks-sdk
    Found existing installation: databricks-sdk 0.30.0

In [0]:
%run ../_resources/00-setup $reset_all_data=false

USE CATALOG `main__build`
using catalog.database `main__build`.`dbdemos_fsi_fraud_detection`

## Data exploration and analysis

Let's review our dataset and start analyze the data we have to detect fraud

### 1- How much fraud are we talking about?
Based on the existing rules, while 3% of the transactions are fraudulent, it takes into account of the 9% of the total amount.

In [0]:
%sql
select 
  is_fraud,
  count(1) as `Transactions`, 
  sum(amount) as `Total Amount` 
from gold_transactions
group by is_fraud

--Visualization Pie chart: Keys: is_fraud, Values: [Transactions, Total Amount]

is_fraud,Transactions,Total Amount
true,179293,6.153292581715001E10
false,5507508,6.177205282463096E11

As expected, financial fraud is by nature very imbalanced between fraudulant and normal transactions

### 2- What type of transactions are associated with fraud?
Reviewing the rules-based model, it appears that most fraudulent transactions are in the category of `Transfer` and `Cash_Out`.

In [0]:
df = spark.sql('select type, is_fraud, count(1) as count from gold_transactions group by type, is_fraud').toPandas()

fig = make_subplots(rows=1, cols=2, specs=[[{'type':'domain'}, {'type':'domain'}]])
fig.add_trace(go.Pie(labels=df[df['is_fraud']]['type'], values=df[df['is_fraud']]['count'], title="Fraud Transactions", hole=0.6), 1, 1)
fig.add_trace(go.Pie(labels=df[~df['is_fraud']]['type'], values=df[~df['is_fraud']]['count'], title="Normal Transactions", hole=0.6) ,1, 2)


## Saving our dataset to Feature Store (Optional)

<img src="https://github.com/QuentinAmbard/databricks-demo/raw/main/product_demos/mlops-end2end-flow-feature-store.png" style="float:right" width="500" />

Once our features are ready, we'll save them in Databricks Feature Store. Under the hood, features store are backed by a Delta Lake table.

This will allow discoverability and reusability of our feature accross our organization, increasing team efficiency.

Feature store will bring traceability and governance in our deployment, knowing which model is dependent of which set of features. It also simplify realtime serving.

Make sure you're using the "Machine Learning" menu to have access to your feature store using the UI.

In [0]:
# Convert to koalas
dataset = spark.table('gold_transactions').dropDuplicates(['id']).pandas_api()
# Drop columns we don't want to use in our model
# Typical DS project would include more transformations / cleanup here
dataset = dataset.drop(columns=['address', 'email', 'firstname', 'lastname', 'creation_date', 'last_activity_date', 'customer_id'])

# Drop missing values
dataset.dropna()
dataset.describe()

             amount  isUnauthorizedOverdraft  newBalanceDest  newBalanceOrig  oldBalanceDest  oldBalanceOrig          step      diffOrig      diffDest     age_group
count  5.686801e+06             5.686801e+06    5.686801e+06    5.686801e+06    5.686801e+06    5.686801e+06  5.686801e+06  5.686801e+06  5.686801e+06  5.686801e+06
mean   1.194439e+05             2.282830e-03    9.965638e+05    2.763623e+06    9.623423e+05    2.773728e+06  2.967341e+02 -1.010442e+04  3.422159e+04  5.003672e+00
std    1.175042e+05             4.772441e-02    8.324467e+05    1.326697e+06    8.067564e+05    1.317442e+06  1.695784e+02  1.623675e+05  1.025538e+05  2.915596e+00
min    0.000000e+00             0.000000e+00   -1.946325e+04   -1.843748e+05   -2.487063e+04   -1.843748e+05  0.000000e+00 -5.103570e+05  0.000000e+00  0.000000e+00
25%    1.136220e+04             0.000000e+00    4.000000e+05    2.046052e+06    3.747497e+05    2.049145e+06  1.660000e+02 -7.721773e+04  0.000000e+00  3.000000e+00
50%    9.591402e+04             0.000000e+00    8.757024e+05    2.915452e+06    8.560332e+05    2.918452e+06  2.880000e+02 -3.352400e+03  0.000000e+00  5.000000e+00
75%    1.768653e+05             0.000000e+00    1.445930e+06    3.470299e+06    1.428829e+06    3.474605e+06  4.390000e+02  1.008559e+05  5.040030e+03  7.000000e+00
max    7.483238e+05             1.000000e+00    2.018745e+07    2.828175e+07    1.999966e+07    2.828175e+07  6.010000e+02  7.483238e+05  4.000000e+05  1.000000e+01

In [0]:
from databricks.feature_store import FeatureStoreClient

fs = FeatureStoreClient()

try:
  #drop table if exists
  fs.drop_table(f'{catalog}.{db}.transactions_features')
except:
  pass

fs.create_table(
  name=f'{catalog}.{db}.transactions_features',
  primary_keys='id',
  schema=dataset.spark.schema(),
  description='These features are derived from the gold_transactions table in the lakehouse.  We created dummy variables for the categorical columns, cleaned up their names, and added a boolean flag for whether the transaction is a fraud or not.  No aggregations were performed.')

fs.write_table(df=dataset.to_spark(), name=f'{catalog}.{db}.transactions_features', mode='overwrite')
features = fs.read_table(f'{catalog}.{db}.transactions_features')
display(features)

2025/11/03 22:27:54 WARNING databricks.ml_features._compute_client._compute_client: Deleting a feature table can lead to unexpected failures in upstream producers and downstream consumers (models, endpoints, and scheduled jobs).
2025/11/03 22:27:58 INFO databricks.ml_features._compute_client._compute_client: Setting columns ['id'] of table 'main.dbdemos_fsi_fraud_detection.transactions_features' to NOT NULL.
2025/11/03 22:28:00 INFO databricks.ml_features._compute_client._compute_client: Setting Primary Keys constraint ['id'] on table 'main.dbdemos_fsi_fraud_detection.transactions_features'.
2025/11/03 22:28:01 INFO databricks.ml_features._compute_client._compute_client: Created feature table 'main.dbdemos_fsi_fraud_detection.transactions_features'.


## Accelerating Fraud detection model creation using MLFlow and Databricks Auto-ML

MLflow is an open source project allowing model tracking, packaging and deployment. Everytime your datascientist team work on a model, Databricks will track all the parameter and data used and will save it. This ensure ML traceability and reproductibility, making it easy to know which model was build using which parameters/data.

### AutoML: A glass-box solution that empowers data teams without taking away control

While Databricks simplify model deployment and governance (MLOps) with MLFlow, bootstraping new ML projects can still be long and inefficient. 

Instead of creating the same boilerplate for each new project, Databricks Auto-ML can automatically generate state of the art models for Classifications, regression, and forecast.


<img width="1000" src="https://github.com/QuentinAmbard/databricks-demo/raw/main/retail/resources/images/auto-ml-full.png"/>


Models can be directly deployed, or instead leverage generated notebooks to boostrap projects with best-practices, saving you weeks of efforts.

<br style="clear: both">

<img style="float: right" width="600" src="https://github.com/QuentinAmbard/databricks-demo/raw/main/retail/resources/images/churn-auto-ml.png"/>

### Using Databricks Auto ML with our Transaction dataset

Auto ML is available in the "Machine Learning" space. All we have to do is start a new Auto-ML experimentation and select the feature table we just created (`gold_transactions`)

Our prediction target is the `is_fraud` column.

Click on Start, and Databricks will do the rest.

While this is done using the UI, you can also leverage the [python API](https://docs.databricks.com/applications/machine-learning/automl.html#automl-python-api-1)

In [0]:
xp_path = "/Shared/dbdemos/experiments/lakehouse-fsi-fraud-detection"
xp_name = f"automl_fraud_{datetime.now().strftime('%Y-%m-%d_%H:%M:%S')}"
try:
    from databricks import automl
    automl_run = automl.classify(
        experiment_name = xp_name,
        experiment_dir = xp_path,
        dataset = features.sample(0.02), #drastically reduce the training size to speedup the demo
        target_col = "is_fraud",
        timeout_minutes = 20
    )
    #Make sure all users can access dbdemos shared experiment
    DBDemos.set_experiment_permission(f"{xp_path}/{xp_name}")
except Exception as e:
    if "cannot import name 'automl'" in str(e) or 'method_whitelist' in str(e):
        # Note: cannot import name 'automl' from 'databricks' likely means you're using serverless. Dbdemos doesn't support autoML serverless API - this will be improved soon.
        # Adding a temporary workaround to make sure it works well for now - ignore this for classic run
        DBDemos.create_mockup_automl_run(f"{xp_path}/{xp_name}", features.sample(0.02).toPandas())
    else:
        raise e

(2025-11-03 22:28:33) WARNING: Hyperopt is deprecated for Databricks runtime for machine learning and will not be pre-installed in the next major version.
2025/11/03 22:28:39 INFO databricks.automl.client.manager: AutoML will optimize for F1 score metric, which is tracked as val_f1_score in the MLflow experiment.
2025/11/03 22:28:40 INFO databricks.automl.shared.databricks_utils: No host name to create absolute URL
2025/11/03 22:28:40 INFO databricks.automl.client.manager: MLflow Experiment ID: 2876013310725865
2025/11/03 22:28:40 INFO databricks.automl.client.manager: MLflow Experiment: #mlflow/experiments/2876013310725865

🏃 View run marvelous-eel-357 at: https://xxxx.cloud.databricks.com/ml/experiments/2876013310725865/runs/eee3ed3caf3647508007571e5c3f879a
🧪 View experiment at: https://xxxx.cloud.databricks.com/ml/experiments/2876013310725865

2025/11/03 22:29:53 INFO databricks.automl.shared.databricks_utils: No host name to create absolute URL
2025/11/03 22:29:53 INFO databricks.automl.client.manager: Data exploration notebook: #notebook/2876013310725872
2025/11/03 22:49:26 INFO databricks.automl.client.manager: AutoML experiment completed successfully.

,Train,Validation,Test
f1_score,0.921,0.908,0.906
recall_score,0.898,0.897,0.894
roc_auc,0.999,0.999,0.999
false_negatives,221.000,73.000,79.000
false_positives,112.000,57.000,60.000
example_count,47650.000,22548.000,22662.000
precision_score,0.946,0.918,0.917
true_positives,1944.000,639.000,666.000
precision_recall_auc,0.985,0.975,0.979
true_negatives,45373.000,21779.000,21857.000
log_loss,0.015,0.013,0.013
score,0.993,0.994,0.994
accuracy_score,0.993,0.994,0.994

Experiment on /Shared/dbdemos/experiments/lakehouse-fsi-fraud-detection/automl_fraud_2025-11-03_22:28:32 was set public

AutoML saved our best model in the MLFlow registry. [Open the dbdemos_fsi fraud model](#mlflow/models/dbdemos_fsi_fraud) to explore its artifact and analyze the parameters used, including traceability to the notebook used for its creation.

If we're ready, we can move this model into Production stage in a click, or using the API.

## Next: deploying our model for Real Time fraud detection serving 

Now that our model has been created with Databricks AutoML, we can start a Model Endpoint to serve low-latencies fraud detection.

We'll be able to rate the Fraud likelihood in ms to reduce fraud in real-time.

Open the [04.3-Model-serving-realtime-inference-fraud]($./04.3-Model-serving-realtime-inference-fraud) to deploy our model or review the notebook generated by AutoML [04.2-automl-generated-notebook-fraud]($./04.2-automl-generated-notebook-fraud).